DROP TABLE IF EXISTS esq_banco.TBL_CUENTA;
DROP TABLE IF EXISTS esq_banco.TBL_CLIENTE;
DROP SCHEMA IF EXISTS esq_banco;

--creando esquema
CREATE SCHEMA esq_banco AUTHORIZATION postgres;

--creando tablas 
CREATE TABLE esq_banco.TBL_CLIENTE(
  CODIGO INTEGER NOT NULL,
  ID VARCHAR(15) NOT NULL,--RUC - DNI
  DATOS VARCHAR(200) NOT NULL,
  TIPOCLIENTE VARCHAR(30) NOT NULL --NATURAL - JURIDICA
);
ALTER TABLE IF EXISTS esq_banco.TBL_CLIENTE ADD CONSTRAINT XPKTBL_CLIENTE PRIMARY KEY(CODIGO);

CREATE TABLE esq_banco.TBL_CUENTA(
  NROCUENTA VARCHAR(40) NULL,
  TIPOCUENTA VARCHAR(40) NULL,
  SALDO NUMERIC NULL,
  CLIENTE INTEGER NOT NULL
); 
ALTER TABLE IF EXISTS esq_banco.TBL_CUENTA ADD CONSTRAINT XPKTBL_CUENTA PRIMARY KEY(NROCUENTA);
ALTER TABLE IF EXISTS esq_banco.TBL_CUENTA ADD CONSTRAINT R1 FOREIGN KEY(CLIENTE) REFERENCES esq_banco.TBL_CLIENTE(CODIGO);

--insertando datos
insert into esq_banco.TBL_CLIENTE(CODIGO,ID,DATOS,TIPOCLIENTE) values(1,'15687626','Miguel Angel Savedra Diaz','NATURAL');
insert into esq_banco.TBL_CLIENTE(CODIGO,ID,DATOS,TIPOCLIENTE) values(2,'20604425567','EMPRESA A','JURIDICA');

insert into esq_banco.TBL_CUENTA(NROCUENTA,TIPOCUENTA,SALDO,CLIENTE) values('34673679877','AHORRO',300.40,1);
insert into esq_banco.TBL_CUENTA(NROCUENTA,TIPOCUENTA,SALDO,CLIENTE) values('50645775245','CORRIENTE',500.40,2);





